# Generated by Django 5.2.12 on 2026-03-19 19:48

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_animals', models.IntegerField()),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', django.contrib.gis.db.models.fields.LineStringField(blank=True, help_text='Optimized route', null=True, srid=4326)),
                ('departure_time', models.DateTimeField()),
                ('estimated_arrival', models.DateTimeField()),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('total_animals', models.IntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_per_animal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(help_text='Visual ear tag or unique identifier', max_length=50, unique=True)),
                ('rfid_tag', models.CharField(blank=True, help_text='Optional electronic RFID', max_length=50, null=True, unique=True)),
                ('name', models.CharField(blank=True, help_text='Optional name given by farmer', max_length=100)),
                ('species', models.CharField(choices=[('GOAT', 'Goat'), ('SHEEP', 'Sheep'), ('CATTLE', 'Cattle')], max_length=10)),
                ('breed', models.CharField(blank=True, max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_date_estimated', models.BooleanField(default=False)),
                ('colour', models.CharField(blank=True, max_length=50)),
                ('distinctive_marks', models.TextField(blank=True)),
                ('current_location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Last known GPS location', null=True, srid=4326)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('DECEASED', 'Deceased')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'livestock',
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('VACCINATION', 'Vaccination'), ('TREATMENT', 'Treatment'), ('CHECKUP', 'Checkup'), ('CERTIFICATION', 'Certification')], max_length=20)),
                ('service_date', models.DateField()),
                ('next_due_date', models.DateField(blank=True, help_text='For vaccinations that require boosters', null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=200)),
                ('treatment_given', models.TextField(blank=True)),
                ('medication_used', models.CharField(blank=True, max_length=200)),
                ('dosage', models.CharField(blank=True, max_length=50)),
                ('certificate_number', models.CharField(blank=True, help_text='Official certificate ID if any', max_length=50, null=True, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('veterinarian', models.ForeignKey(limit_choices_to={'profile__user_type': 'VET'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_records_given', to=settings.AUTH_USER_MODEL)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='livestock.livestock')),
            ],
        ),
        migrations.CreateModel(
            name='HealthCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('valid_until', models.DateField()),
                ('is_valid', models.BooleanField(default=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='certificates/qrcodes/')),
                ('pdf_file', models.FileField(blank=True, upload_to='certificates/pdfs/')),
                ('issued_by', models.ForeignKey(limit_choices_to={'profile__user_type': 'VET'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_issued', to=settings.AUTH_USER_MODEL)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='livestock.livestock')),
            ],
        ),
        migrations.CreateModel(
            name='MarketListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('listed_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('WITHDRAWN', 'Withdrawn')], default='ACTIVE', max_length=20)),
                ('views', models.IntegerField(default=0)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='livestock.livestock')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('REMINDER', 'Reminder'), ('ALERT', 'Alert'), ('CONFIRMATION', 'Confirmation'), ('INFO', 'Information')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_via_sms', models.BooleanField(default=False)),
                ('sms_delivery_status', models.CharField(blank=True, max_length=20)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfflineAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text="e.g., 'Livestock'", max_length=50)),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('data', models.JSONField(help_text='Serialized data of the object')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(help_text='e.g., Kiserian, Ilbisil', max_length=100)),
                ('species', models.CharField(choices=[('GOAT', 'Goat'), ('SHEEP', 'Sheep'), ('CATTLE', 'Cattle')], max_length=10)),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('source', models.CharField(blank=True, help_text='e.g., Slaughterhouse, Trader reports', max_length=50)),
            ],
            options={
                'indexes': [models.Index(fields=['market', 'species', 'date'], name='livestock_p_market_95b2b6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=50)),
                ('is_completed', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='livestock.marketlisting')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_count', models.IntegerField()),
                ('origin', django.contrib.gis.db.models.fields.PointField(help_text='Pickup location (boma)', srid=4326)),
                ('destination', django.contrib.gis.db.models.fields.PointField(help_text='Market or slaughterhouse', srid=4326)),
                ('preferred_date', models.DateField()),
                ('preferred_time_window', models.CharField(choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('ANY', 'Any')], default='ANY', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('POOLED', 'Pooled'), ('ASSIGNED', 'Assigned'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pooling_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='livestock.poolinggroup')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='poolinggroup',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pooling_groups', to='livestock.trip'),
        ),
        migrations.CreateModel(
            name='TripAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaded_at', models.DateTimeField(blank=True, null=True)),
                ('unloaded_at', models.DateTimeField(blank=True, null=True)),
                ('health_checked', models.BooleanField(default=False)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.livestock')),
            ],
        ),
        migrations.CreateModel(
            name='TripManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('collection_time', models.DateTimeField(blank=True, null=True)),
                ('farmer_confirmed', models.BooleanField(default=False)),
                ('animals', models.ManyToManyField(through='livestock.TripAnimal', to='livestock.livestock')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.transportrequest')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifests', to='livestock.trip')),
            ],
        ),
        migrations.AddField(
            model_name='tripanimal',
            name='trip_manifest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.tripmanifest'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?254\\d{9}$', message='Enter a valid Kenyan phone number')])),
                ('user_type', models.CharField(choices=[('PASTORALIST', 'Pastoralist'), ('VET', 'Veterinarian'), ('TRANSPORTER', 'Transporter'), ('BUYER', 'Buyer'), ('ADMIN', 'Administrator')], default='PASTORALIST', max_length=20)),
                ('county', models.CharField(default='Kajiado', max_length=100)),
                ('sub_county', models.CharField(blank=True, max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('preferred_language', models.CharField(default='Maa', max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(help_text='e.g., Livestock Carrier, Pickup', max_length=30)),
                ('capacity', models.IntegerField(help_text='Number of animals (sheep/goat equivalent)')),
                ('has_ventilation', models.BooleanField(default=True)),
                ('has_partitions', models.BooleanField(default=True)),
                ('insurance_valid_until', models.DateField()),
                ('inspection_valid_until', models.DateField()),
                ('current_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(limit_choices_to={'profile__user_type': 'TRANSPORTER'}, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='livestock.vehicle'),
        ),
        migrations.AddField(
            model_name='poolinggroup',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pooling_groups', to='livestock.vehicle'),
        ),
        migrations.AddIndex(
            model_name='livestock',
            index=models.Index(fields=['owner', 'status'], name='livestock_l_owner_i_419639_idx'),
        ),
        migrations.AddIndex(
            model_name='livestock',
            index=models.Index(fields=['species'], name='livestock_l_species_2f52d1_idx'),
        ),
        migrations.AddIndex(
            model_name='healthrecord',
            index=models.Index(fields=['next_due_date'], name='livestock_h_next_du_831f50_idx'),
        ),
        migrations.AddIndex(
            model_name='transportrequest',
            index=models.Index(fields=['status', 'preferred_date'], name='livestock_t_status_a96be5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tripanimal',
            unique_together={('trip_manifest', 'animal')},
        ),
    ]
