# Generated by Django 5.2.12 on 2026-04-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='livestock_images/'),
        ),
    ]
