# Generated by Django 5.2.12 on 2026-04-20 17:23

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_livestock_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='livestock',
            name='health_status_manual',
            field=models.CharField(blank=True, choices=[('GREEN', 'Healthy'), ('YELLOW', 'Due Soon'), ('RED', 'Needs Care')], default='', help_text='Manually set health status (overrides computed value)', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_listing_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_transport_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='destination_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='transaction',
            name='mpesa_checkout_request_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='origin_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('MARKETPLACE', 'Animal Purchase'), ('TRANSPORT', 'Transport Payment')], default='MARKETPLACE', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transport_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='livestock.transportrequest'),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='destination_name',
            field=models.CharField(default='', help_text='Market name', max_length=200),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='mpesa_receipt',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='trip_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='vehicle_size_preference',
            field=models.CharField(choices=[('PICKUP', 'Pickup (up to 10 animals)'), ('MEDIUM', 'Medium Truck (10–30 animals)'), ('LARGE', 'Large Carrier (30+ animals)')], default='PICKUP', max_length=20),
        ),
        migrations.AddField(
            model_name='trip',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='veterinarian',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__user_type': 'VET'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_records_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='current_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='livestock/images/'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='rfid_tag',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='tag_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('REMINDER', 'Reminder'), ('ALERT', 'Alert'), ('CONFIRMATION', 'Confirmation'), ('INFO', 'Information'), ('PAYMENT', 'Payment'), ('VET_REQUEST', 'Vet Request')], max_length=20),
        ),
        migrations.AlterField(
            model_name='offlineaction',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='offlineaction',
            name='model_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pricedata',
            name='market',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pricedata',
            name='source',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='livestock.marketlisting'),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='destination',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Destination coordinates', srid=4326),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='origin',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Pickup location (GPS)', srid=4326),
        ),
        migrations.AlterField(
            model_name='trip',
            name='route',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('PICKUP', 'Pickup (up to 10 animals)'), ('MEDIUM', 'Medium Truck (10–30 animals)'), ('LARGE', 'Large Carrier (30+ animals)')], max_length=30),
        ),
    ]
