# Generated by Django 5.2.12 on 2026-04-20 21:42

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0003_livestock_health_status_manual_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportrequest',
            name='destination',
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='accepted_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__user_type': 'TRANSPORTER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='health_status_manual',
            field=models.CharField(blank=True, choices=[('GREEN', 'Healthy'), ('YELLOW', 'Due Soon'), ('RED', 'Needs Care')], default='GREEN', help_text='Manually set health status', max_length=10),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='destination_name',
            field=models.CharField(default='', help_text='Market or destination name', max_length=200),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='origin',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Pickup GPS location', srid=4326),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('POOLED', 'Pooled'), ('ASSIGNED', 'Assigned'), ('IN_TRANSIT', 'In Transit'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='capacity',
            field=models.IntegerField(),
        ),
    ]
