# Generated by Django 5.2.12 on 2026-04-21 09:38

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0004_remove_transportrequest_destination_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_vet_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='health_status_manual',
            field=models.CharField(blank=True, choices=[('GREEN', 'Healthy'), ('YELLOW', 'Due Soon'), ('RED', 'Needs Care')], default='GREEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('REMINDER', 'Reminder'), ('ALERT', 'Alert'), ('CONFIRMATION', 'Confirmation'), ('INFO', 'Information'), ('PAYMENT', 'Payment'), ('VET_REQUEST', 'Vet Request'), ('VET_ACCEPTED', 'Vet Accepted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('MARKETPLACE', 'Animal Purchase'), ('TRANSPORT', 'Transport Payment'), ('VET', 'Veterinary Payment')], default='MARKETPLACE', max_length=20),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='destination_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='origin',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.CreateModel(
            name='VetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('urgency', models.CharField(choices=[('LOW', 'Low — routine check'), ('MEDIUM', 'Medium — needs attention'), ('HIGH', 'High — urgent')], default='MEDIUM', max_length=10)),
                ('symptoms', models.TextField(help_text='Describe what you observe')),
                ('additional_notes', models.TextField(blank=True)),
                ('pastoralist_location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Pastoralist GPS location', null=True, srid=4326)),
                ('pastoralist_location_name', models.CharField(blank=True, help_text='e.g. Near Kajiado town, off Namanga road', max_length=200)),
                ('vet_current_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Fee set by vet on acceptance', max_digits=8, null=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=50)),
                ('mpesa_checkout_request_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_requests', to='livestock.livestock')),
                ('pastoralist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_requests_made', to=settings.AUTH_USER_MODEL)),
                ('vet', models.ForeignKey(blank=True, limit_choices_to={'profile__user_type': 'VET'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vet_requests_accepted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='vet_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='livestock.vetrequest'),
        ),
        migrations.AddIndex(
            model_name='vetrequest',
            index=models.Index(fields=['status', 'created_at'], name='livestock_v_status_d64bd1_idx'),
        ),
    ]
