# Generated by Django 5.2.12 on 2026-04-22 17:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0005_notification_related_vet_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequest',
            name='driver_current_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Driver live GPS — updated every 15 s after acceptance', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='vetrequest',
            name='consultation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='vetrequest',
            name='pastoralist_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='vetrequest',
            name='pastoralist_location_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vetrequest',
            name='symptoms',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vetrequest',
            name='urgency',
            field=models.CharField(choices=[('LOW', 'Low — routine'), ('MEDIUM', 'Medium — needs attention'), ('HIGH', 'High — urgent')], default='MEDIUM', max_length=10),
        ),
    ]
