# Generated by Django 5.2.12 on 2026-04-30 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0006_transportrequest_driver_current_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PASTORALIST', 'Pastoralist'), ('VET', 'Veterinarian'), ('TRANSPORTER', 'Transporter'), ('BUYER', 'Buyer'), ('ADMIN', 'Administrator'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('action', models.CharField(help_text='Human-readable description', max_length=300)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PATCH', 'PATCH'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='GET', max_length=10)),
                ('endpoint', models.CharField(max_length=200)),
                ('status_code', models.IntegerField(default=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='livestock_a_user_id_78b9c2_idx'), models.Index(fields=['role', '-timestamp'], name='livestock_a_role_c4f9a5_idx'), models.Index(fields=['-timestamp'], name='livestock_a_timesta_58cf30_idx')],
            },
        ),
    ]
